# Generated by Django 6.0.7 on 2026-08-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=30, unique=True)),
                ('vehicle', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=80, unique=True)),
                ('port', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Booking Confirmed', 'Booking Confirmed'), ('In Transit', 'In Transit'), ('Arrived at Port', 'Arrived at Port'), ('Customs Clearance', 'Customs Clearance'), ('Released', 'Released'), ('Delivered', 'Delivered')], default='Booking Confirmed', max_length=40)),
                ('eta', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notification_type', models.CharField(default='info', max_length=20)),
                ('time_label', models.CharField(default='Now', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Front.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=80)),
                ('sha256_hash', models.CharField(max_length=128)),
                ('status', models.CharField(default='Verified', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Front.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=250)),
                ('sha256_digest', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='Front.shipment')),
            ],
        ),
    ]
