# Generated by Django 6.1 on 2026-08-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='file_size',
            field=models.CharField(blank=True, default='1.8 MB', max_length=30),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='uploaded_by',
            field=models.CharField(blank=True, default='GT Motors Ltd.', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, default='Modjo Dry Port, Ethiopia', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='duty_amount',
            field=models.CharField(blank=True, default='ETB 1,250,000', max_length=60),
        ),
        migrations.AddField(
            model_name='shipment',
            name='image',
            field=models.CharField(blank=True, default='/static/images/land_cruiser.png', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='importer_name',
            field=models.CharField(blank=True, default='GT Motors Ltd.', max_length=150),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='Front.shipment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Front.shipment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_label',
            field=models.CharField(default='Just now', max_length=50),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('sender_role', models.CharField(default='Customs Officer', max_length=100)),
                ('recipient', models.CharField(default='GT Motors Ltd.', max_length=150)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='Front.shipment')),
            ],
        ),
    ]
