# Generated by Django 6.1 on 2026-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(unique=True)),
                ('role', models.CharField(choices=[('SYSTEM_ADMIN', 'System adminstrator'), ('IMPORTER', 'Importer'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('POST_SHIPPING', 'Post/Shipping Office'), ('FREIGHT_FORWARDER', 'Freight Forwarder'), ('STAKEHOLDER', 'General Stakeholder')], default='STAKEHOLDER', max_length=30)),
                ('account_status', models.CharField(default='active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
